apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: databases
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: databases
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10G
---
#tODO: change Deployment to StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: databases
  labels:
    app: mysql
    tier: databases
    version: "5.7"
spec:
  selector: 
    matchLabels:
      app: mysql
  serviceName: "mysql-svc"
  replicas: 1
  # podManagementPolicy: OrderedReady
  # updateStrategy: 
  #   type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-user-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-secret
              key: password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-secret
              key: rootPassword
        ports:
        - containerPort: 3306
          name: mysql-port
        volumeMounts:
          - name: default
            mountPath: "/etc/mysql/conf.d"
            # readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 256M
          limits:
            cpu: 500m
            memory: 500M
      volumes:
      - name: default
        configMap:
          name: mysql-config
  volumeClaimTemplates:
  - metadata:
      name: mysql-pv-claim
      namespace: databases
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 1G
    